-- MySQL Script generated by MySQL Workbench
-- Sun Nov 15 14:47:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sunflower
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sunflower
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sunflower` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sunflower` ;

-- -----------------------------------------------------
-- Table `sunflower`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sunflower`.`course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `price` DECIMAL(21,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_course_title` (`title` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sunflower`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sunflower`.`teacher` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(200) NOT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sunflower`.`online_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sunflower`.`online_class` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `course_id` BIGINT NULL DEFAULT NULL,
  `teacher_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_online_class_course_id` (`course_id` ASC) VISIBLE,
  INDEX `fk_online_class_teacher_id` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_online_class_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `sunflower`.`course` (`id`),
  CONSTRAINT `fk_online_class_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `sunflower`.`teacher` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sunflower`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sunflower`.`student` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(200) NOT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sunflower`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sunflower`.`receipt` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `receipt_no` VARCHAR(255) NOT NULL,
  `receipt_date` DATE NOT NULL,
  `amount` DECIMAL(21,2) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `student_id` BIGINT NULL DEFAULT NULL,
  `course_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receipt_student_id` (`student_id` ASC) VISIBLE,
  INDEX `fk_receipt_course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_receipt_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `sunflower`.`course` (`id`),
  CONSTRAINT `fk_receipt_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `sunflower`.`student` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sunflower`.`student_online_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sunflower`.`student_online_class` (
  `online_class_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  PRIMARY KEY (`student_id`, `online_class_id`),
  INDEX `fk_student_online_class_online_class_id` (`online_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_online_class_online_class_id`
    FOREIGN KEY (`online_class_id`)
    REFERENCES `sunflower`.`online_class` (`id`),
  CONSTRAINT `fk_student_online_class_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `sunflower`.`student` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
